/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagementRouteRouteImport } from './routes/_management/route'
import { Route as ManagementIndexRouteImport } from './routes/_management/index'
import { Route as ManagementVisitsIndexRouteImport } from './routes/_management/visits/index'
import { Route as ManagementSettingsIndexRouteImport } from './routes/_management/settings/index'
import { Route as ManagementPrisonsIndexRouteImport } from './routes/_management/prisons/index'
import { Route as ManagementOfficersIndexRouteImport } from './routes/_management/officers/index'
import { Route as ManagementMovementsIndexRouteImport } from './routes/_management/movements/index'
import { Route as ManagementInmatesIndexRouteImport } from './routes/_management/inmates/index'
import { Route as ManagementDocumentationsIndexRouteImport } from './routes/_management/documentations/index'

const ManagementRouteRoute = ManagementRouteRouteImport.update({
  id: '/_management',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementVisitsIndexRoute = ManagementVisitsIndexRouteImport.update({
  id: '/visits/',
  path: '/visits/',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementSettingsIndexRoute = ManagementSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementPrisonsIndexRoute = ManagementPrisonsIndexRouteImport.update({
  id: '/prisons/',
  path: '/prisons/',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementOfficersIndexRoute = ManagementOfficersIndexRouteImport.update({
  id: '/officers/',
  path: '/officers/',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementMovementsIndexRoute =
  ManagementMovementsIndexRouteImport.update({
    id: '/movements/',
    path: '/movements/',
    getParentRoute: () => ManagementRouteRoute,
  } as any)
const ManagementInmatesIndexRoute = ManagementInmatesIndexRouteImport.update({
  id: '/inmates/',
  path: '/inmates/',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementDocumentationsIndexRoute =
  ManagementDocumentationsIndexRouteImport.update({
    id: '/documentations/',
    path: '/documentations/',
    getParentRoute: () => ManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ManagementIndexRoute
  '/documentations/': typeof ManagementDocumentationsIndexRoute
  '/inmates/': typeof ManagementInmatesIndexRoute
  '/movements/': typeof ManagementMovementsIndexRoute
  '/officers/': typeof ManagementOfficersIndexRoute
  '/prisons/': typeof ManagementPrisonsIndexRoute
  '/settings/': typeof ManagementSettingsIndexRoute
  '/visits/': typeof ManagementVisitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ManagementIndexRoute
  '/documentations': typeof ManagementDocumentationsIndexRoute
  '/inmates': typeof ManagementInmatesIndexRoute
  '/movements': typeof ManagementMovementsIndexRoute
  '/officers': typeof ManagementOfficersIndexRoute
  '/prisons': typeof ManagementPrisonsIndexRoute
  '/settings': typeof ManagementSettingsIndexRoute
  '/visits': typeof ManagementVisitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_management': typeof ManagementRouteRouteWithChildren
  '/_management/': typeof ManagementIndexRoute
  '/_management/documentations/': typeof ManagementDocumentationsIndexRoute
  '/_management/inmates/': typeof ManagementInmatesIndexRoute
  '/_management/movements/': typeof ManagementMovementsIndexRoute
  '/_management/officers/': typeof ManagementOfficersIndexRoute
  '/_management/prisons/': typeof ManagementPrisonsIndexRoute
  '/_management/settings/': typeof ManagementSettingsIndexRoute
  '/_management/visits/': typeof ManagementVisitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentations/'
    | '/inmates/'
    | '/movements/'
    | '/officers/'
    | '/prisons/'
    | '/settings/'
    | '/visits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentations'
    | '/inmates'
    | '/movements'
    | '/officers'
    | '/prisons'
    | '/settings'
    | '/visits'
  id:
    | '__root__'
    | '/_management'
    | '/_management/'
    | '/_management/documentations/'
    | '/_management/inmates/'
    | '/_management/movements/'
    | '/_management/officers/'
    | '/_management/prisons/'
    | '/_management/settings/'
    | '/_management/visits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ManagementRouteRoute: typeof ManagementRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_management': {
      id: '/_management'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ManagementRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_management/': {
      id: '/_management/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/_management/visits/': {
      id: '/_management/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof ManagementVisitsIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/_management/settings/': {
      id: '/_management/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ManagementSettingsIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/_management/prisons/': {
      id: '/_management/prisons/'
      path: '/prisons'
      fullPath: '/prisons/'
      preLoaderRoute: typeof ManagementPrisonsIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/_management/officers/': {
      id: '/_management/officers/'
      path: '/officers'
      fullPath: '/officers/'
      preLoaderRoute: typeof ManagementOfficersIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/_management/movements/': {
      id: '/_management/movements/'
      path: '/movements'
      fullPath: '/movements/'
      preLoaderRoute: typeof ManagementMovementsIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/_management/inmates/': {
      id: '/_management/inmates/'
      path: '/inmates'
      fullPath: '/inmates/'
      preLoaderRoute: typeof ManagementInmatesIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/_management/documentations/': {
      id: '/_management/documentations/'
      path: '/documentations'
      fullPath: '/documentations/'
      preLoaderRoute: typeof ManagementDocumentationsIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
  }
}

interface ManagementRouteRouteChildren {
  ManagementIndexRoute: typeof ManagementIndexRoute
  ManagementDocumentationsIndexRoute: typeof ManagementDocumentationsIndexRoute
  ManagementInmatesIndexRoute: typeof ManagementInmatesIndexRoute
  ManagementMovementsIndexRoute: typeof ManagementMovementsIndexRoute
  ManagementOfficersIndexRoute: typeof ManagementOfficersIndexRoute
  ManagementPrisonsIndexRoute: typeof ManagementPrisonsIndexRoute
  ManagementSettingsIndexRoute: typeof ManagementSettingsIndexRoute
  ManagementVisitsIndexRoute: typeof ManagementVisitsIndexRoute
}

const ManagementRouteRouteChildren: ManagementRouteRouteChildren = {
  ManagementIndexRoute: ManagementIndexRoute,
  ManagementDocumentationsIndexRoute: ManagementDocumentationsIndexRoute,
  ManagementInmatesIndexRoute: ManagementInmatesIndexRoute,
  ManagementMovementsIndexRoute: ManagementMovementsIndexRoute,
  ManagementOfficersIndexRoute: ManagementOfficersIndexRoute,
  ManagementPrisonsIndexRoute: ManagementPrisonsIndexRoute,
  ManagementSettingsIndexRoute: ManagementSettingsIndexRoute,
  ManagementVisitsIndexRoute: ManagementVisitsIndexRoute,
}

const ManagementRouteRouteWithChildren = ManagementRouteRoute._addFileChildren(
  ManagementRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ManagementRouteRoute: ManagementRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
